In [3]:
import numpy as np

In [5]:
xtrain=np.load(r"D:\\4-2\\Capstone Design2\\MS-G3D-master\\data\\ntu\\xsub\\train_data_joint.npy")
ytrain=np.load(r"D:\\4-2\\Capstone Design2\\MS-G3D-master\data\\ntu\xsub\\train_label.pkl.npy", allow_pickle=True)

In [11]:
#이런 순서라면 이미 3 channel이다.
#마지막 2만 없애면 됨
print(xtrain.shape)

(40091, 3, 300, 25, 2)


In [15]:
print(np.array(ytrain[0]).shape, np.array(ytrain[1]).shape)

(40091,) (40091,)


In [44]:
#중간 dimension을 여러 번 복붙 가능
x=np.tile(xtrain, [1,1,1,3,1])

In [45]:
x.shape

(40091, 3, 300, 75, 2)

In [62]:
print(x)

[[[[[-1.02243675e-02  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00]
    [ 1.50561510e-02  0.00000000e+00]
    ...
    [-1.47018908e-02  0.00000000e+00]
    [-2.74152905e-02  0.00000000e+00]
    [ 7.92306289e-03  0.00000000e+00]]

   [[-1.06783882e-02  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00]
    [ 1.55046368e-02  0.00000000e+00]
    ...
    [ 1.58521552e-02  0.00000000e+00]
    [-3.43220681e-02  0.00000000e+00]
    [-5.44905430e-03  0.00000000e+00]]

   [[-1.10689560e-02  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00]
    [ 1.56757571e-02  0.00000000e+00]
    ...
    [ 5.81341423e-03  0.00000000e+00]
    [-2.29697824e-02  0.00000000e+00]
    [ 4.52771457e-03  0.00000000e+00]]

   ...

   [[-2.57555582e-02  0.00000000e+00]
    [ 0.00000000e+00  0.00000000e+00]
    [ 3.09102386e-02  0.00000000e+00]
    ...
    [ 4.40035798e-02  0.00000000e+00]
    [ 1.56366813e-03  0.00000000e+00]
    [ 8.36131908e-03  0.00000000e+00]]

   [[-2.48473380e-02  0.00000000e+00]
  

In [59]:
#맨 끝에 있는 2를 첫 번째 data만 가져가고 날림
x_=x[:,:,:,:,0]

In [61]:
x_.shape

(40091, 3, 300, 75)

In [60]:
print(x_)

[[[[-1.02243675e-02  0.00000000e+00  1.50561510e-02 ... -1.47018908e-02
    -2.74152905e-02  7.92306289e-03]
   [-1.06783882e-02  0.00000000e+00  1.55046368e-02 ...  1.58521552e-02
    -3.43220681e-02 -5.44905430e-03]
   [-1.10689560e-02  0.00000000e+00  1.56757571e-02 ...  5.81341423e-03
    -2.29697824e-02  4.52771457e-03]
   ...
   [-2.57555582e-02  0.00000000e+00  3.09102386e-02 ...  4.40035798e-02
     1.56366813e-03  8.36131908e-03]
   [-2.48473380e-02  0.00000000e+00  3.08201816e-02 ...  3.79619785e-02
    -4.96287365e-03  6.26891432e-03]
   [-2.50770450e-02  0.00000000e+00  2.96519641e-02 ...  3.33288610e-02
     2.65973131e-03 -1.42972975e-03]]

  [[ 2.33980664e-03  0.00000000e+00  7.59654539e-03 ...  2.42134586e-01
     2.42249131e-01  2.23440081e-01]
   [ 2.72775930e-03  0.00000000e+00  7.19846878e-03 ...  2.14909777e-01
     2.17625916e-01  2.22365201e-01]
   [ 2.21143570e-03  0.00000000e+00  7.47715216e-03 ...  2.34422773e-01
     2.34325036e-01  2.28992373e-01]
   ...
   

In [71]:
x=[1,2,3,-1]

In [74]:
x[-2:]

[3, -1]

In [76]:
xtrain.shape

(40091, 3, 300, 25, 2)

In [77]:
xtrain[0].shape

(3, 300, 25, 2)

In [78]:
xtrain_=xtrain[:,:,:,:,0]
xtrain_.shape

(40091, 3, 300, 25)

In [82]:
xtrain_[0][0][0]

array([-0.01022437,  0.        ,  0.01505615, -0.00538309, -0.13106515,
       -0.1268647 , -0.010965  , -0.00656537,  0.13835813,  0.21200149,
        0.06342897,  0.00894634, -0.05519095, -0.04218946, -0.03375929,
       -0.0800776 ,  0.06187384,  0.09835823,  0.10648835,  0.06225711,
        0.01038549,  0.00819522, -0.01470189, -0.02741529,  0.00792306],
      dtype=float32)

In [83]:
xtrain_[0][0][1]

array([-0.01067839,  0.        ,  0.01550464, -0.00671272, -0.13173419,
       -0.12752505, -0.01253424, -0.01253726,  0.13831533,  0.21199733,
        0.04730244, -0.00152769, -0.05577403, -0.04430159, -0.03809969,
       -0.02730738,  0.0616494 ,  0.09603515,  0.10925373,  0.067591  ,
        0.01072324,  0.00077486,  0.01585216, -0.03432207, -0.00544905],
      dtype=float32)

In [98]:
swapidx=[20,19,18,17,   24, 25, 12, 1, 10, 9,    4, 3, 21, 2, 1,   5, 6, 7, 8, 23, 22,     13, 14, 15, 16]

In [93]:
test=np.array([i for i in range(1, 26)])

In [94]:
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
def swapelem(input_data, swapidx):
    swapidx=np.array(swapidx)
    swapidx-=1
    #print(swapidx)
    newlst=[]
    for i in swapidx:
        newlst.append(input_data[i])
    return newlst

In [109]:
swapelem(test, swapidx)

[19 18 17 16 23 24 11  0  9  8  3  2 20  1  0  4  5  6  7 22 21 12 13 14
 15]


[19,
 23,
 18,
 24,
 2,
 8,
 12,
 5,
 10,
 9,
 17,
 3,
 21,
 1,
 5,
 6,
 11,
 7,
 14,
 20,
 22,
 13,
 15,
 16,
 4]