<h3>Numpy Practice</h3>

<p>Purpose of this file is to practice some useful tools and libraries for machine learning<br>
This file refers book named "Machine Learning with Python CookBook".
</p>

In [18]:
import numpy as np
import pandas as pd

In [12]:
vector1=np.array([1,2,3])
vector2=np.ndarray([1,2,3])    #This way is not recommended
vector3=np.ndarray((3,))
vector4=np.asarray([1,2,3])

In [20]:
vector1, vector2, vector3, vector4

(array([1, 2, 3]), array([[[0., 0., 0.],
         [0., 0., 0.]]]), array([1.35386043e-311, 0.00000000e+000, 1.35383331e-311]), array([1, 2, 3]))

In [21]:
copied_vec=np.asarray(vector1)
copied_vec

array([1, 2, 3])

In [24]:
vector1[0]=10000
copied_vec

array([10000,     2,     3])

<p>The method np.asarray shares the same address space with parameter.<br> So if element changes at original object. Element of newly initialized oject also changed like copied vector example above.
(0f course, concept of address and pointer is not used in Python.)
</p>

In [2]:
empty=np.empty((2,3))

In [3]:
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
zero_array=np.zeros((3,3))
one_array=np.ones((1,5))

In [6]:
one_array

array([[1., 1., 1., 1., 1.]])

In [7]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
zero_array+10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [10]:
fill_matrix=np.full((3,4),-9)

In [11]:
fill_matrix

array([[-9, -9, -9, -9],
       [-9, -9, -9, -9],
       [-9, -9, -9, -9]])

In [13]:
from scipy import sparse

In [14]:
matrix=np.array([[1,2,3],[3,2,1],[0,0,0]])
sparse_mat=sparse.csr_matrix(matrix)
sparse_mat

<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 6 stored elements in Compressed Sparse Row format>

In [15]:
print(sparse_mat)

  (0, 0)	1
  (0, 1)	2
  (0, 2)	3
  (1, 0)	3
  (1, 1)	2
  (1, 2)	1


<p>This sparse matrix is useful when most of element are 0s.<br>
To initialize sparse matrix, use function "sparse.csr_matrix()" from library scipy
</p>

In [20]:
print(sparse_mat[1])

  (0, 0)	3
  (0, 1)	2
  (0, 2)	1


In [23]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
matrix[:2, :1]

array([[1],
       [4]])

In [27]:
print("row, column: ",matrix.shape)
print("row * cloumn: ", matrix.size)
print("dimension: ", matrix.ndim)

row, column:  (3, 3)
row * cloumn:  9
dimension:  2


In [28]:
matrix.dtype

dtype('int32')

In [29]:
matrix.itemsize

4

In [30]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
flat=lambda x: x if x>0 else 0
vectorize_mat=np.array([[1,2,3],[-1,-10,3]])
flat_mat=np.vectorize(flat)
flat_mat(vectorize_mat)

array([[1, 2, 3],
       [0, 0, 3]])

<p>np.vectorize() is numpy function that takes function(including lambda function) as parameter.<br>
Then, the vectorized object can be used as a function that acts on numpy objects
</p>

In [42]:
np.empty((3))

array([ 8.12069742e-312,  0.00000000e+000, -4.94065646e-324])

In [7]:
arr=np.array([[1,8,3],[4,5,9],[7,2,6]])

In [11]:
print("MAX: ", arr.max())
print("MIN: ", arr.min())
print("MIN in col: ", arr.min(axis=0))

MAX:  9
MIN:  1
MIN in col:  [1 2 3]


In [12]:
print("MIN in row, keep dimension: ", arr.min(axis=1, keepdims=True))

MIN in row, keep dimension:  [[1]
 [4]
 [2]]


In [17]:
print("MEAN: ", arr.mean())
print("MEAN: ", )
print("STD: ", arr.std())
print("STD with delta degree of freedom of 1: ", arr.std(ddof=1))

MEAN:  5.0
MEAN: 
STD:  2.581988897471611
STD with delta degree of freedom of 1:  2.7386127875258306


In [19]:
df=pd.DataFrame(arr.flatten())

In [20]:
df

0
0  1
1  8
2  3
3  4
4  5
5  9
6  7
7  2
8  6

In [21]:
df.mean()

0    5.0
dtype: float64

In [23]:
df.std()

0    2.738613
dtype: float64

In [25]:
df.std(ddof=2)

0    2.9277
dtype: float64

In [26]:
df.var()

0    7.5
dtype: float64

In [27]:
arr.shape

(3, 3)

In [28]:
arr

array([[1, 8, 3],
       [4, 5, 9],
       [7, 2, 6]])

In [30]:
arr.reshape((1,-1))

array([[1, 8, 3, 4, 5, 9, 7, 2, 6]])

In [32]:
arr.T

array([[1, 4, 7],
       [8, 5, 2],
       [3, 9, 6]])

In [37]:
np.linalg.det(arr)

243.00000000000017

In [38]:
arr.diagonal()

array([1, 5, 6])

In [41]:
np.dot(arr,np.linalg.inv(arr))

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

In [42]:
np.random.seed(10)
np.random.random((2,3))

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

<p>Random function creates random number between 0 and 1 with given size</p>

In [46]:
np.random.shuffle(arr)

In [48]:
arr

array([[7, 2, 6],
       [1, 8, 3],
       [4, 5, 9]])

In [50]:
np.random.permutation(arr)

array([[4, 5, 9],
       [1, 8, 3],
       [7, 2, 6]])

In [51]:
arr

array([[7, 2, 6],
       [1, 8, 3],
       [4, 5, 9]])

<p>function np.random.permutation copies given vector and returns randomly shuffled vector.</p>