<h3>Numpy Practice</h3>

<p>Purpose of this file is to practice some useful tools and libraries for machine learning<br>
This file refers book named "Machine Learning with Python CookBook".
</p>

In [1]:
import numpy as np

In [12]:
vector1=np.array([1,2,3])
vector2=np.ndarray([1,2,3])    #This way is not recommended
vector3=np.ndarray((3,))
vector4=np.asarray([1,2,3])

In [20]:
vector1, vector2, vector3, vector4

(array([1, 2, 3]), array([[[0., 0., 0.],
         [0., 0., 0.]]]), array([1.35386043e-311, 0.00000000e+000, 1.35383331e-311]), array([1, 2, 3]))

In [21]:
copied_vec=np.asarray(vector1)
copied_vec

array([1, 2, 3])

In [24]:
vector1[0]=10000
copied_vec

array([10000,     2,     3])

<p>The method np.asarray shares the same address space with parameter.<br> So if element changes at original object. Element of newly initialized oject also changed like copied vector example above.
(0f course, concept of address and pointer is not used in Python.)
</p>