In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x=torch.ones(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [3]:
x=torch.zeros(3,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
torch.manual_seed(2)
x=torch.rand(3,2)
print(x)

tensor([[0.6147, 0.3810],
        [0.6371, 0.4745],
        [0.7136, 0.6190]])


In [5]:
x=torch.rand(3,3)
print(x)

tensor([[0.4425, 0.0958, 0.6142],
        [0.0573, 0.5657, 0.5332],
        [0.3901, 0.9088, 0.5334]])


In [6]:
x=torch.tensor([[1,2],[3,4,],[5,6]])
print(x[:,1])
print(x[0, :])

tensor([2, 4, 6])
tensor([1, 2])


In [7]:
y=x[1,1]
y

tensor(4)

In [8]:
x=torch.tensor([[1,2],[3,4],[5,6]])
y=x.view(2,3)
print(y)
y=x.view(6,-1)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [9]:
x=torch.ones([3,2])
y=torch.ones([3,2])

z=x+y
z=torch.add(x, y) #both methods are same
print(z)

z=x-y
z=torch.sub(x, y) #both methods are same
print(z)

y.add_(x)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [10]:
a=np.random.randn(5)
print(a)
a_pt=torch.from_numpy(a)
print(a_pt)
print(type(a), type(a_pt))

[-2.21171295  0.83075    -0.58420385  0.37856611 -1.07090857]
tensor([-2.2117,  0.8307, -0.5842,  0.3786, -1.0709], dtype=torch.float64)
<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [11]:
USE_CUDA = torch.cuda.is_available()
DEVICE = torch.device("cuda" if USE_CUDA else "cpu")

In [14]:
print(DEVICE, USE_CUDA)

cpu False


In [15]:
DEVICE

device(type='cpu')

In [17]:
a=torch.ones(3,2,device=DEVICE)
b=torch.ones(3,2, device=DEVICE)
c=a+b

In [19]:
c=c.cpu() #can move variable c to cpu

In [20]:
x=torch.ones(3,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y=x+5
print(y)

z=y*y+1
print(z)

t=torch.sum(z)
print(t)


tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)
tensor(222., grad_fn=<SumBackward0>)


In [22]:
t.backward()
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [30]:
x=torch.tensor([[1,2],[3,4],[5,6],[1,2]], dtype=torch.float32, requires_grad=True)
y=x+5
y.requires_grad_(True)
print(y)

z=y*y+1
z.requires_grad_(True)
print(z)

t=torch.sum(z)
print(t)

t.backward()
print(x.grad)

tensor([[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [ 6.,  7.]], grad_fn=<AddBackward0>)
tensor([[ 37.,  50.],
        [ 65.,  82.],
        [101., 122.],
        [ 37.,  50.]], grad_fn=<AddBackward0>)
tensor(544., grad_fn=<SumBackward0>)
tensor([[12., 14.],
        [16., 18.],
        [20., 22.],
        [12., 14.]])


In [31]:
print(z.grad)
print(y.grad)
print(x.grad)

None
None
tensor([[12., 14.],
        [16., 18.],
        [20., 22.],
        [12., 14.]])


![autograd-formula](./pics/autograd.jpg)