In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_data=[1.0, 2.0, 3.0]
y_data=[2.0, 4.0, 6.0]

w=torch.tensor([1.0], requires_grad=True)

In [3]:
def forward(x):
    return w*x

def loss(x, y):
    y_pred=forward(x)
    return (y_pred-y)**2

In [4]:
#Before training
print("pridict before training ", 4, forward(4).item())


for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l=loss(x_val, y_val)
        l.backward() #doing backpropagation
        print("\tgrad: ", x_val, y_val, w.grad.item())
        w.data=w.data-0.01*w.grad.item()
        
        #Munually zero the gradients after updating weights
        w.grad.data.zero_() 
        
    print(f"Epoch: {epoch} | Loss: {l.item()}")
    
#After training
print("pridict after training ", 4, forward(4).item())

pridict before training  4 4.0
	grad:  1.0 2.0 -2.0
	grad:  2.0 4.0 -7.840000152587891
	grad:  3.0 6.0 -16.228801727294922
Epoch: 0 | Loss: 7.315943717956543
	grad:  1.0 2.0 -1.478623867034912
	grad:  2.0 4.0 -5.796205520629883
	grad:  3.0 6.0 -11.998146057128906
Epoch: 1 | Loss: 3.9987640380859375
	grad:  1.0 2.0 -1.0931644439697266
	grad:  2.0 4.0 -4.285204887390137
	grad:  3.0 6.0 -8.870372772216797
Epoch: 2 | Loss: 2.1856532096862793
	grad:  1.0 2.0 -0.8081896305084229
	grad:  2.0 4.0 -3.1681032180786133
	grad:  3.0 6.0 -6.557973861694336
Epoch: 3 | Loss: 1.1946394443511963
	grad:  1.0 2.0 -0.5975041389465332
	grad:  2.0 4.0 -2.3422164916992188
	grad:  3.0 6.0 -4.848389625549316
Epoch: 4 | Loss: 0.6529689431190491
	grad:  1.0 2.0 -0.4417421817779541
	grad:  2.0 4.0 -1.7316293716430664
	grad:  3.0 6.0 -3.58447265625
Epoch: 5 | Loss: 0.35690122842788696
	grad:  1.0 2.0 -0.3265852928161621
	grad:  2.0 4.0 -1.2802143096923828
	grad:  3.0 6.0 -2.650045394897461
Epoch: 6 | Loss: 0.195076

In [5]:
w

tensor([1.9512], requires_grad=True)

In [6]:
w.grad

tensor([0.])

In [7]:
w.grad.item()

0.0

In [8]:
w.grad.data

tensor([0.])

In [9]:
w.grad.zero_()

tensor([0.])

tensor 객체는 .data와 .grad를 사용할 수 있다. 