<h2>Pytorch's some basic torch methods</h2>

In [1]:
import torch

In [2]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
print(x.shape)
print(x.size())
print(x.ndimension())

torch.Size([3, 3])
torch.Size([3, 3])
2


In [5]:
#increasing the dimension of tensor.
x=torch.unsqueeze(x, 0)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [6]:
#decrease the dimension of tensor.
x=torch.squeeze(x)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
#view is similar to np.rehape()
y=x.view(-1)
print(y)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
w=torch.randn(5,4, dtype=torch.float)
x=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print("Weight size:", w.size())
print("x size: ", x.size())
print("Weight: ",w)
print("x: ", x)

Weight size: torch.Size([5, 4])
x size:  torch.Size([4, 2])
Weight:  tensor([[ 0.1297,  0.0626, -0.0604, -0.1303],
        [ 0.2744,  2.7175, -0.6008, -0.5668],
        [-1.3323,  0.7200, -0.0476, -1.1583],
        [ 0.8430, -0.6350, -1.7392, -1.1513],
        [-1.6214, -0.4234,  0.9110, -0.1254]])
x:  tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [14]:
b=torch.randn(5,2, dtype=torch.float)
print("b size: ", b.size())
print("b: ", b)

b size:  torch.Size([5, 2])
b:  tensor([[-0.6982, -0.3619],
        [-0.0069, -0.8838],
        [ 1.7085,  0.4816],
        [-0.0204, -1.1429],
        [-1.1664,  0.1461]])


In [17]:
wx=torch.mm(w,x.float())
result=wx+b
print("result size: ", result.size())
print("result: ", result)

result size:  torch.Size([5, 2])
result:  tensor([[ -1.5944,  -1.2565],
        [  1.4485,   2.3959],
        [ -5.8098,  -8.8548],
        [-17.8374, -21.6424],
        [ -0.3806,  -0.3273]])
