In [19]:
import numpy as np

In [20]:
arr=np.array([1,2,3])

In [21]:
arr.shape

(3,)

In [26]:
arr=np.array([1,2,3])
arr.shape

(3,)

In [27]:
arr

array([1, 2, 3])

In [29]:
arr.reshape((None,))

TypeError: 'NoneType' object cannot be interpreted as an integer

In [18]:
arr.reshape(None, )

array([1, 2, 3])

In [25]:
arr

array([1, 2, 3])

In [32]:
x=(None, 0)

In [33]:
x

(None, 0)